version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: intellect_clone_db
    environment:
      POSTGRES_USER: intellect_user
      POSTGRES_PASSWORD: intellect_password
      POSTGRES_DB: intellect_clone
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: