-- Complete data population for Manufacturing Portal
-- Run this in your Supabase SQL Editor

-- First, ensure the demo user exists
INSERT INTO "users" ("id", "email", "name", "role", "department", "createdAt", "updatedAt") 
VALUES 
('demo-user-id', 'demo@company.com', 'Demo User', 'USER', 'Manufacturing', NOW(), NOW()),
('admin-user-id', 'admin@company.com', 'Admin User', 'ADMIN', 'Quality Assurance', NOW(), NOW()),
('manager-user-id', 'manager@company.com', 'Manager User', 'MANAGER', 'Management', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

-- Add more sample products from your CSV
INSERT INTO "products" ("id", "brand", "sku", "productName", "healthCategory", "therapeuticPlatform", "nutrientType", "format", "numberOfActives", "bottleCount", "unitCount", "manufacturer", "containsIron", "createdAt", "updatedAt") VALUES
('prod-BFCAPSADEK', 'Bariatric Fusion', 'BFCAPSADEK', 'Multivitamin Three Per Day ADEK 90ct Capsule', 'Foundational Health & Wellness', 'Metabolic', 'Multivitamins, Vitamins & Minerals', 'Capsule', 'Multiple', '90', 90, 'BRH', true, NOW(), NOW()),
('prod-BFCAPSADEK270', 'Bariatric Fusion', 'BFCAPSADEK270', 'Multivitamin Three Per Day ADEK 270ct Capsule', 'Foundational Health & Wellness', 'Metabolic', 'Multivitamins, Vitamins & Minerals', 'Capsule', 'Multiple', '270', 270, 'BRH', true, NOW(), NOW()),
('prod-BFCAPSB50', 'Bariatric Fusion', 'BFCAPSB50', 'B-50 Complex 90ct', 'Foundational Health & Wellness', 'Metabolic', 'Multivitamins, Vitamins & Minerals', 'Capsule', 'Multiple', '90', 90, 'BRH', false, NOW(), NOW()),
('prod-BFCAPSBIOTIN5000', 'Bariatric Fusion', 'BFCAPSBIOTIN5000', 'Biotin 5mg', 'Foundational Health & Wellness', 'Metabolic', 'Multivitamins, Vitamins & Minerals', 'Capsule', 'Single', '90', 90, 'BRH', false, NOW(), NOW()),
('prod-BFCAPSDIGESTIVE', 'Bariatric Fusion', 'BFCAPSDIGESTIVE', 'Digestive Enzyme capsules', 'Gastrointestinal Health', 'Digestive Health', 'Enzymes', 'Capsule', 'Multiple', '60', 60, 'Deerland/ADM', false, NOW(), NOW()),
('prod-BFCAPSENERGY', 'Bariatric Fusion', 'BFCAPSENERGY', 'Energy Support 60ct', 'Energy', 'Health Vitality & Lifestyle', 'Herbs & Extracts', 'Capsule', 'Multiple', '60', 60, 'BRH', false, NOW(), NOW()),
('prod-BFCAPSGLP30', 'Bariatric Fusion', 'BFCAPSGLP30', 'GLP-1 Boost & Balance', 'Metabolism & Healthy Weight', 'Metabolic', 'Herbs & Extracts', 'Capsule', 'Multiple', '30', 30, 'BRH', false, NOW(), NOW()),
('prod-BFCAPSGLPMULTI30', 'Bariatric Fusion', 'BFCAPSGLPMULTI30', 'GLP-ONE Multivitamin', 'Foundational Health & Wellness', 'Metabolic', 'Multivitamins, Vitamins & Minerals', 'Capsule', 'Multiple', '30', 30, '', false, NOW(), NOW()),
('prod-BFCAPSHSNR', 'Bariatric Fusion', 'BFCAPSHSNR', 'Hair Skin Nails Rejuvenator 60ct', 'Womens Health', 'Metabolic', 'Multivitamins, Vitamins & Minerals', 'Capsule', 'Multiple', '60', 60, 'BRH', false, NOW(), NOW()),
('prod-BFCAPSHSNR120', 'Bariatric Fusion', 'BFCAPSHSNR120', 'Hair Skin Nails Rejuvenator 120ct', 'Womens Health', 'Metabolic', 'Multivitamins, Vitamins & Minerals', 'Capsule', 'Multiple', '120', 120, 'BRH', false, NOW(), NOW()),
('prod-BFCAPSIRON30', 'Bariatric Fusion', 'BFCAPSIRON30', 'Multivitamin One Per Day with 45mg Iron 30ct Capsules', 'Foundational Health & Wellness', 'Metabolic', 'Multivitamins, Vitamins & Minerals', 'Capsule', 'Multiple', '30', 30, 'BRH', true, NOW(), NOW()),
('prod-BFCAPSIRON90', 'Bariatric Fusion', 'BFCAPSIRON90', 'Multivitamin One Per Day with 45mg Iron 90ct Capsules', 'Foundational Health & Wellness', 'Metabolic', 'Multivitamins, Vitamins & Minerals', 'Capsule', 'Multiple', '90', 90, 'BRH', true, NOW(), NOW()),
('prod-BFCAPSIRONC45', 'Bariatric Fusion', 'BFCAPSIRONC45', 'Iron 45mg with Vit C Capsule 60ct', 'Foundational Health & Wellness', 'Metabolic', 'Multivitamins, Vitamins & Minerals', 'Capsule', 'Multiple', '60', 60, 'BRH', true, NOW(), NOW()),
('prod-BFCAPSIRONC60', 'Bariatric Fusion', 'BFCAPSIRONC60', 'Iron 60mg with Vit C Capsule 60ct', 'Foundational Health & Wellness', 'Metabolic', 'Multivitamins, Vitamins & Minerals', 'Capsule', 'Multiple', '60', 60, 'BRH', true, NOW(), NOW()),
('prod-BFCAPSIRONFREE30', 'Bariatric Fusion', 'BFCAPSIRONFREE30', 'One-Per-Day Multivitamin without Iron 30 ct', 'Foundational Health & Wellness', 'Metabolic', 'Multivitamins, Vitamins & Minerals', 'Capsule', 'Multiple', '30', 30, '', false, NOW(), NOW()),
('prod-BFCAPSIRONFREE90', 'Bariatric Fusion', 'BFCAPSIRONFREE90', 'One-Per-Day Multivitamin without Iron 90 ct', 'Foundational Health & Wellness', 'Metabolic', 'Multivitamins, Vitamins & Minerals', 'Capsule', 'Multiple', '90', 90, '', false, NOW(), NOW()),
('prod-BFCAPSMULTI180', 'Bariatric Fusion', 'BFCAPSMULTI180', 'Multivitamin Two Per Day NO Iron 180ct Capsules', 'Foundational Health & Wellness', 'Metabolic', 'Multivitamins, Vitamins & Minerals', 'Capsule', 'Multiple', '180', 180, 'BRH', false, NOW(), NOW()),
('prod-BFCAPSMULTI60', 'Bariatric Fusion', 'BFCAPSMULTI60', 'Multivitamin Two Per Day NO Iron 60ct Capsules', 'Foundational Health & Wellness', 'Metabolic', 'Multivitamins, Vitamins & Minerals', 'Capsule', 'Multiple', '60', 60, 'BRH', false, NOW(), NOW())
ON CONFLICT (sku) DO NOTHING;

-- Create all 10 QMS templates
INSERT INTO "templates" ("id", "name", "description", "type", "content", "isActive", "createdBy", "createdAt", "updatedAt") VALUES
('tmpl-raw-material', 'Raw Material Specification', 'Template for raw material specifications and quality requirements', 'RAW_MATERIAL_SPEC', '{"materialInfo":{"materialName":"","supplierName":"","lotNumber":"","receiptDate":""},"specifications":{"appearance":"","color":"","odor":"","moisture":"","purity":""},"tests":[],"storage":"","handling":"","approvals":{"qualityManager":"","regulatoryApproval":"","finalApproval":""}}', true, 'demo-user-id', NOW(), NOW()),

('tmpl-finished-goods', 'Finished Goods Specification', 'Template for finished product specifications', 'FINISHED_GOODS_SPEC', '{"productInfo":{"productName":"","sku":"","version":"1.0","effectiveDate":""},"specifications":{"appearance":"","color":"","odor":"","taste":"","physicalForm":""},"ingredients":[],"nutritionalInfo":{"servingSize":"","servingsPerContainer":"","nutrients":[]},"qualityTests":[],"packaging":{"primaryPackaging":"","secondaryPackaging":"","labeling":""},"storage":{"conditions":"","shelfLife":""},"approvals":{"qualityAssurance":"","regulatory":"","management":""}}', true, 'demo-user-id', NOW(), NOW()),

('tmpl-ccr', 'Critical Control Record (CCR)', 'Template for critical control records and monitoring', 'CCR', '{"batchInfo":{"batchNumber":"","productName":"","manufacturingDate":"","expiryDate":""},"criticalControlPoints":[{"step":"","hazard":"","criticalLimit":"","monitoring":"","correctionAction":""}],"monitoring":[{"time":"","temperature":"","pH":"","operator":"","action":""}],"correctionActions":[],"verification":"","approvals":{"productionManager":"","qualityManager":"","finalApproval":""}}', true, 'demo-user-id', NOW(), NOW()),

('tmpl-label-manuscript', 'Label Manuscript', 'Template for product label manuscripts and artwork specifications', 'LABEL_MANUSCRIPT', '{"productInfo":{"productName":"","sku":"","version":"","artworkVersion":""},"labelSpecs":{"dimensions":"","material":"","colors":"","finish":"","printMethod":""},"textContent":{"productName":"","brandName":"","netWeight":"","ingredients":"","directions":"","warnings":""},"nutritionalPanel":{"servingSize":"","calories":"","nutrients":[]},"claims":[],"warnings":[],"approvals":{"marketing":"","regulatory":"","qualityAssurance":"","finalApproval":""}}', true, 'demo-user-id', NOW(), NOW()),

('tmpl-psf', 'Product Specification File (PSF)', 'Template for comprehensive product specification files', 'PSF', '{"productDetails":{"name":"","sku":"","version":"","category":"","description":""},"formulation":{"activeIngredients":[],"inactiveIngredients":[],"totalWeight":""},"manufacturing":{"process":"","equipment":"","batchSize":"","yield":""},"packaging":{"primaryPackage":"","secondaryPackage":"","shippingContainer":""},"labeling":{"frontPanel":"","backPanel":"","nutritionFacts":""},"storage":{"temperature":"","humidity":"","lightProtection":"","shelfLife":""},"distribution":{"shippingRequirements":"","handlingInstructions":""},"approvals":{"formulation":"","manufacturing":"","packaging":"","regulatory":"","finalApproval":""}}', true, 'demo-user-id', NOW(), NOW()),

('tmpl-bom', 'Bill of Materials (BOM)', 'Template for bill of materials and component specifications', 'BOM', '{"productInfo":{"productName":"","sku":"","version":"","revision":"","batchSize":""},"materials":[{"itemNumber":"","description":"","supplier":"","quantity":"","unit":"","cost":"","specifications":""}],"packaging":[{"component":"","supplier":"","quantity":"","unit":"","cost":""}],"labels":[{"labelType":"","supplier":"","quantity":"","specifications":""}],"totalWeight":"","yield":"","costSummary":{"materialCost":"","packagingCost":"","labelCost":"","totalCost":""},"approvals":{"procurement":"","manufacturing":"","qualityAssurance":"","finalApproval":""}}', true, 'demo-user-id', NOW(), NOW()),

('tmpl-mmr', 'Master Manufacturing Record (MMR)', 'Template for master manufacturing records and procedures', 'MMR', '{"productInfo":{"productName":"","batchSize":"","version":"","revision":"","effectiveDate":""},"ingredients":[{"ingredient":"","quantity":"","unit":"","specifications":"","supplier":"","lotNumber":""}],"equipment":[{"equipmentId":"","description":"","settings":"","calibrationDue":""}],"procedures":[{"step":"","instruction":"","criticalParameter":"","acceptanceCriteria":"","operator":""}],"qualityControls":[{"testPoint":"","test":"","method":"","acceptanceCriteria":"","frequency":""}],"packaging":[{"component":"","quantity":"","specifications":"","supplier":""}],"approvals":{"production":"","quality":"","regulatory":"","finalApproval":""}}', true, 'demo-user-id', NOW(), NOW()),

('tmpl-coa', 'Certificate of Analysis (COA)', 'Template for certificate of analysis documents', 'COA', '{"batchInfo":{"batchNumber":"","productName":"","lotNumber":"","manufacturingDate":"","expiryDate":"","testDate":"","releaseDate":""},"specifications":[{"parameter":"","specification":"","method":"","result":"","passFail":""}],"microbiological":[{"test":"","method":"","specification":"","result":"","passFail":""}],"physical":[{"parameter":"","specification":"","result":"","passFail":""}],"chemical":[{"parameter":"","specification":"","result":"","passFail":""}],"conclusion":"","testedBy":"","reviewedBy":"","approvedBy":"","approvals":{"analyst":"","supervisor":"","qualityManager":"","finalApproval":""}}', true, 'demo-user-id', NOW(), NOW()),

('tmpl-coc', 'Certificate of Compliance (COC)', 'Template for certificate of compliance documents', 'COC', '{"productInfo":{"productName":"","batchNumber":"","lotNumber":"","complianceDate":"","certificateNumber":""},"regulations":[{"regulation":"","requirement":"","complianceStatus":"","evidence":""}],"standards":[{"standard":"","requirement":"","complianceStatus":"","testMethod":"","result":""}],"certifications":[{"certification":"","issuingBody":"","certificateNumber":"","expiryDate":"","scope":""}],"complianceStatement":"This product has been manufactured and tested in accordance with applicable regulations and standards.","manufacturingFacility":{"name":"","address":"","license":"","inspectionDate":""},"approvals":{"qualityManager":"","regulatoryAffairs":"","authorizedSignatory":"","finalApproval":""}}', true, 'demo-user-id', NOW(), NOW()),

('tmpl-pis', 'Product Information Sheet (PIS)', 'Template for product information sheets', 'PIS', '{"productInfo":{"productName":"","sku":"","version":"","lastUpdated":"","category":""},"description":"","intendedUse":"","targetAudience":"","indications":"","dosage":{"recommendedDose":"","frequency":"","duration":"","specialInstructions":""},"ingredients":[{"name":"","amount":"","unit":"","function":"","source":""}],"nutritionalInformation":{"servingSize":"","nutrients":[]},"warnings":["Keep out of reach of children","Do not exceed recommended dose","Consult healthcare professional before use"],"contraindications":[],"sideEffects":"","storageInstructions":"","manufacturerInfo":{"name":"","address":"","phone":"","email":"","website":""},"regulatoryInfo":{"fdaStatus":"","claims":"","disclaimers":""},"approvals":{"marketing":"","regulatory":"","medical":"","finalApproval":""}}', true, 'demo-user-id', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;